import type { Metadata } from 'next';
import './globals.scss';
import { inter, poppins, dancingScript } from '@/assets/fonts';
import Header from '@/components/Header/Header';

export const metadata: Metadata = {
  title: 'Mamans de Sallanches',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${poppins.variable} ${dancingScript.variable}`}
      >
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}

// on ajoute en class du body les classes des polices de caractères. Cela permet de les charger en asynchrone et de les utiliser dans le reste de l'application.

// TODO :
//  - personnaliser les metadata
//  - ajouter un favicon
