import type { Metadata } from 'next';
import './globals.scss';
import { inter, poppins } from '@/assets/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${poppins.variable}`}>
        {children}
      </body>
    </html>
  );
}

// on ajoute en class du body les classes des polices de caractères. Cela permet de les charger en asynchrone et de les utiliser dans le reste de l'application.

// TODO :
//  - personnaliser les metadata
//  - ajouter un favicon
